version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "11:05"
  groups:
    actions:
      patterns:
        - "*"

- package-ecosystem: "github-actions" # See documentation for possible values
  directory: ".github/workflows" # Location of package manifests
  schedule:
    interval: "monthly"
  groups:
    actions:
      patterns:
        - "*"
