name: CI

on:
  push:
  pull_request:
  schedule:
    # Weekly Thursday 6 AM build
    # * is a special character in YAML so you have to quote this string
    - cron: '0 6 * * 4'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  initial_check:
    name: Mandatory checks before CI
    runs-on: ubuntu-latest
    steps:
    - name: Check base branch
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea  # v7.0.1
      if: github.event_name == 'pull_request'
      with:
        script: |
          const allowed_basebranch = 'master';
          const pr = context.payload.pull_request;
          if (pr.base.ref !== allowed_basebranch) {
            core.setFailed(`PR opened against ${pr.base.ref}, not ${allowed_basebranch}`);
          } else {
            core.info(`PR opened correctly against ${allowed_basebranch}`);
          }

  # The rest only run if above are done

  pep:
    runs-on: ubuntu-latest
    needs: initial_check
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
      with:
        python-version: '3.x'
    - name: Lint with flake8
      run: |
        python -m pip install --upgrade pip flake8
        flake8 wss_tools --count
    # Make sure that packaging will work
    - name: pep517 build
      run: |
        python -m pip install --upgrade setuptools build "twine>=3.3"
        python -m build --sdist .
        twine check --strict dist/*

  tests:
    runs-on: ubuntu-latest
    needs: initial_check
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
      with:
        python-version: '3.11'
    - name: Install and build
      run: |
        sudo apt-get update
        sudo apt-get install libxml2-utils
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -e .[test]
    - name: Test
      run: pytest

  dev_deps_tests:
    runs-on: ubuntu-latest
    needs: initial_check
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
      with:
        python-version: '3.12'
    - name: Install and build
      run: |
        sudo apt-get update
        sudo apt-get install libxml2-utils
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install astropy -i https://pypi.anaconda.org/astropy/simple --pre -U
        python -m pip install git+https://github.com/ejeschke/ginga.git@main#egg=ginga
        python -m pip install git+https://github.com/spacetelescope/stginga.git@master#egg=stginga
        python -m pip install -e .[test]
    - name: Test with dev deps
      run: pytest

  link_check:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
    - name: Set up Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
      with:
        python-version: '3.12'
    - name: Install and build
      run: |
        python -m pip install --upgrade pip setuptools wheel sphinx-astropy
        python -m pip install -e .
    - name: Docs link check
      run: |
        cd docs
        make linkcheck
      shell: bash
